CREATE TABLE IF NOT EXISTS parent_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255),
    task VARCHAR(255),
    status VARCHAR(50),
    priority INT,
    context CLOB  -- ✅ H2 uses CLOB for JSON-like text storage
);

CREATE TABLE IF NOT EXISTS sub_job (
    id BIGINT PRIMARY KEY,
    parent_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    priority INT NOT NULL,
    context CLOB NOT NULL,
    is_dependent BOOLEAN DEFAULT FALSE,
    dependency_id BIGINT NULL,  -- ✅ ADD THIS COLUMN
    FOREIGN KEY (parent_id) REFERENCES parent_job(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE  (
    JOB_INSTANCE_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VERSION BIGINT,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION  (
    JOB_EXECUTION_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL,
    END_TIME TIMESTAMP DEFAULT NULL,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP,
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
        REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_PARAMS  (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(100) NOT NULL,
    PARAMETER_VALUE VARCHAR(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION  (
    STEP_EXECUTION_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL,
    END_TIME TIMESTAMP DEFAULT NULL,
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP,
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT  (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
        REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT  (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT CLOB,
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE SEQUENCE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_SEQ;

DELETE FROM sub_job;
DELETE FROM parent_job;

INSERT INTO parent_job (id, type, task, status, priority, context) VALUES
(1, 'DISCOVERY', 'DISCOVER', 'CREATED', 2,
 '{"resourceTypeDetails": {"1": "VIRTUAL_NETWORK", "2": "SUBNET", "3": "VIRTUAL_MACHINE", "4": "DISK", "5": "NETWORK_INTERFACE"},
   "credential": {"accessKey": "dfefewe34234223", "secret": "sfeser3242434"}}');

INSERT INTO sub_job (id, parent_id, status, priority, context, is_dependent, dependency_id) VALUES
(1, 1, 'CREATED', 2, '{"resourceType":"VIRTUAL_NETWORK"}', 0, NULL),
(2, 1, 'CREATED', 2, '{"DependsOn":"VIRTUAL_NETWORK","resourceType":"SUBNET"}', 1, 1),
(3, 1, 'CREATED', 2, '{"resourceType":"VIRTUAL_MACHINE"}', 0, NULL),
(4, 1, 'CREATED', 2, '{"resourceType":"DISK"}', 0, NULL),
(5, 1, 'CREATED', 2, '{"resourceType":"NETWORK_INTERFACE"}', 0, NULL);

--INSERT INTO parent_job (id, type, task, status, priority, context) VALUES
--(2, 'DISCOVERY', 'DISCOVER', 'CREATED', 1,
-- '{"resourceTypeDetails": {"1": "VIRTUAL_NETWORK", "2": "SUBNET", "3": "VIRTUAL_MACHINE", "4": "DISK", "5": "NETWORK_INTERFACE"},
--   "credential": {"accessKey": "dfefewe34234223", "secret": "sfeser3242434"}}');
--
--INSERT INTO sub_job (id, parent_id, status, priority, context, is_dependent, dependency_id) VALUES
--(6, 2, 'CREATED', 1, '{"resourceType":"VIRTUAL_NETWORK"}', 0, NULL),
--(7, 2, 'CREATED', 1, '{"DependsOn":"VIRTUAL_NETWORK","resourceType":"SUBNET"}', 1, 6),
--(8, 2, 'CREATED', 1, '{"resourceType":"VIRTUAL_MACHINE"}', 0, NULL),
--(9, 2, 'CREATED', 1, '{"resourceType":"DISK"}', 0, NULL),
--(10, 2, 'CREATED', 1, '{"resourceType":"NETWORK_INTERFACE"}', 0, NULL);
--
--INSERT INTO parent_job (id, type, task, status, priority, context) VALUES
--(3, 'DISCOVERY', 'DISCOVER', 'CREATED', 2,
-- '{"resourceTypeDetails": {"1": "VIRTUAL_NETWORK", "2": "SUBNET", "3": "VIRTUAL_MACHINE", "4": "DISK", "5": "NETWORK_INTERFACE"},
--   "credential": {"accessKey": "dfefewe34234223", "secret": "sfeser3242434"}}');
--
--INSERT INTO sub_job (id, parent_id, status, priority, context, is_dependent, dependency_id) VALUES
--(11, 3, 'CREATED', 2, '{"resourceType":"VIRTUAL_NETWORK"}', 0, NULL),
--(12, 3, 'CREATED', 2, '{"DependsOn":"VIRTUAL_NETWORK","resourceType":"SUBNET"}', 1, 11),
--(13, 3, 'CREATED', 2, '{"resourceType":"VIRTUAL_MACHINE"}', 0, NULL),
--(14, 3, 'CREATED', 2, '{"resourceType":"DISK"}', 0, NULL),
--(15, 3, 'CREATED', 2, '{"resourceType":"NETWORK_INTERFACE"}', 0, NULL);
--
--INSERT INTO parent_job (id, type, task, status, priority, context) VALUES
--(4, 'DISCOVERY', 'DISCOVER', 'CREATED', 2,
-- '{"resourceTypeDetails": {"1": "VIRTUAL_NETWORK", "2": "SUBNET", "3": "VIRTUAL_MACHINE", "4": "DISK", "5": "NETWORK_INTERFACE"},
--   "credential": {"accessKey": "dfefewe34234223", "secret": "sfeser3242434"}}');
--
--INSERT INTO sub_job (id, parent_id, status, priority, context, is_dependent, dependency_id) VALUES
--(16, 4, 'CREATED', 2, '{"resourceType":"VIRTUAL_NETWORK"}', 0, NULL),
--(17, 4, 'CREATED', 2, '{"DependsOn":"VIRTUAL_NETWORK","resourceType":"SUBNET"}', 1, 16),
--(18, 4, 'CREATED', 2, '{"resourceType":"VIRTUAL_MACHINE"}', 0, NULL),
--(19, 4, 'CREATED', 2, '{"resourceType":"DISK"}', 0, NULL),
--(20, 4, 'CREATED', 2, '{"resourceType":"NETWORK_INTERFACE"}', 0, NULL);
--
--INSERT INTO parent_job (id, type, task, status, priority, context) VALUES
--(5, 'DISCOVERY', 'DISCOVER', 'CREATED', 2,
-- '{"resourceTypeDetails": {"1": "VIRTUAL_NETWORK", "2": "SUBNET", "3": "VIRTUAL_MACHINE", "4": "DISK", "5": "NETWORK_INTERFACE"},
--   "credential": {"accessKey": "dfefewe34234223", "secret": "sfeser3242434"}}');
--
--INSERT INTO sub_job (id, parent_id, status, priority, context, is_dependent, dependency_id) VALUES
--(21, 5, 'CREATED', 2, '{"resourceType":"VIRTUAL_NETWORK"}', 0, NULL),
--(22, 5, 'CREATED', 2, '{"DependsOn":"VIRTUAL_NETWORK","resourceType":"SUBNET"}', 1, 21),
--(23, 5, 'CREATED', 2, '{"resourceType":"VIRTUAL_MACHINE"}', 0, NULL),
--(24, 5, 'CREATED', 2, '{"resourceType":"DISK"}', 0, NULL),
--(25, 5, 'CREATED', 2, '{"resourceType":"NETWORK_INTERFACE"}', 0, NULL);
--
--INSERT INTO parent_job (id, type, task, status, priority, context) VALUES
--(6, 'DISCOVERY', 'DISCOVER', 'CREATED', 2,
-- '{"resourceTypeDetails": {"1": "VIRTUAL_NETWORK", "2": "SUBNET", "3": "VIRTUAL_MACHINE", "4": "DISK", "5": "NETWORK_INTERFACE"},
--   "credential": {"accessKey": "dfefewe34234223", "secret": "sfeser3242434"}}');
--
--INSERT INTO sub_job (id, parent_id, status, priority, context, is_dependent, dependency_id) VALUES
--(26, 6, 'CREATED', 2, '{"resourceType":"VIRTUAL_NETWORK"}', 0, NULL),
--(27, 6, 'CREATED', 2, '{"DependsOn":"VIRTUAL_NETWORK","resourceType":"SUBNET"}', 1, 26),
--(28, 6, 'CREATED', 2, '{"resourceType":"VIRTUAL_MACHINE"}', 0, NULL),
--(29, 6, 'CREATED', 2, '{"resourceType":"DISK"}', 0, NULL),
--(30, 6, 'CREATED', 2, '{"resourceType":"NETWORK_INTERFACE"}', 0, NULL);
--
--INSERT INTO parent_job (id, type, task, status, priority, context) VALUES
--(7, 'DISCOVERY', 'DISCOVER', 'CREATED', 2,
-- '{"resourceTypeDetails": {"1": "VIRTUAL_NETWORK", "2": "SUBNET", "3": "VIRTUAL_MACHINE", "4": "DISK", "5": "NETWORK_INTERFACE"},
--   "credential": {"accessKey": "dfefewe34234223", "secret": "sfeser3242434"}}');
--
--INSERT INTO sub_job (id, parent_id, status, priority, context, is_dependent, dependency_id) VALUES
--(31, 7, 'CREATED', 2, '{"resourceType":"VIRTUAL_NETWORK"}', 0, NULL),
--(32, 7, 'CREATED', 2, '{"DependsOn":"VIRTUAL_NETWORK","resourceType":"SUBNET"}', 1, 31),
--(33, 7, 'CREATED', 2, '{"resourceType":"VIRTUAL_MACHINE"}', 0, NULL),
--(34, 7, 'CREATED', 2, '{"resourceType":"DISK"}', 0, NULL),
--(35, 7, 'CREATED', 2, '{"resourceType":"NETWORK_INTERFACE"}', 0, NULL);
--
--INSERT INTO parent_job (id, type, task, status, priority, context) VALUES
--(8, 'DISCOVERY', 'DISCOVER', 'CREATED', 2,
-- '{"resourceTypeDetails": {"1": "VIRTUAL_NETWORK", "2": "SUBNET", "3": "VIRTUAL_MACHINE", "4": "DISK", "5": "NETWORK_INTERFACE"},
--   "credential": {"accessKey": "dfefewe34234223", "secret": "sfeser3242434"}}');
--
--INSERT INTO sub_job (id, parent_id, status, priority, context, is_dependent, dependency_id) VALUES
--(36, 8, 'CREATED', 2, '{"resourceType":"VIRTUAL_NETWORK"}', 0, NULL),
--(37, 8, 'CREATED', 2, '{"DependsOn":"VIRTUAL_NETWORK","resourceType":"SUBNET"}', 1, 36),
--(38, 8, 'CREATED', 2, '{"resourceType":"VIRTUAL_MACHINE"}', 0, NULL),
--(39, 8, 'CREATED', 2, '{"resourceType":"DISK"}', 0, NULL),
--(40, 8, 'CREATED', 2, '{"resourceType":"NETWORK_INTERFACE"}', 0, NULL);
--
--INSERT INTO parent_job (id, type, task, status, priority, context) VALUES
--(9, 'DISCOVERY', 'DISCOVER', 'CREATED', 2,
-- '{"resourceTypeDetails": {"1": "VIRTUAL_NETWORK", "2": "SUBNET", "3": "VIRTUAL_MACHINE", "4": "DISK", "5": "NETWORK_INTERFACE"},
--   "credential": {"accessKey": "dfefewe34234223", "secret": "sfeser3242434"}}');
--
--INSERT INTO sub_job (id, parent_id, status, priority, context, is_dependent, dependency_id) VALUES
--(41, 9, 'CREATED', 2, '{"resourceType":"VIRTUAL_NETWORK"}', 0, NULL),
--(42, 9, 'CREATED', 2, '{"DependsOn":"VIRTUAL_NETWORK","resourceType":"SUBNET"}', 1, 41),
--(43, 9, 'CREATED', 2, '{"resourceType":"VIRTUAL_MACHINE"}', 0, NULL),
--(44, 9, 'CREATED', 2, '{"resourceType":"DISK"}', 0, NULL),
--(45, 9, 'CREATED', 2, '{"resourceType":"NETWORK_INTERFACE"}', 0, NULL);
--
--INSERT INTO parent_job (id, type, task, status, priority, context) VALUES
--(10, 'DISCOVERY', 'DISCOVER', 'CREATED', 2,
-- '{"resourceTypeDetails": {"1": "VIRTUAL_NETWORK", "2": "SUBNET", "3": "VIRTUAL_MACHINE", "4": "DISK", "5": "NETWORK_INTERFACE"},
--   "credential": {"accessKey": "dfefewe34234223", "secret": "sfeser3242434"}}');
--
--INSERT INTO sub_job (id, parent_id, status, priority, context, is_dependent, dependency_id) VALUES
--(46, 10, 'CREATED', 2, '{"resourceType":"VIRTUAL_NETWORK"}', 0, NULL),
--(47, 10, 'CREATED', 2, '{"DependsOn":"VIRTUAL_NETWORK","resourceType":"SUBNET"}', 1, 46),
--(48, 10, 'CREATED', 2, '{"resourceType":"VIRTUAL_MACHINE"}', 0, NULL),
--(49, 10, 'CREATED', 2, '{"resourceType":"DISK"}', 0, NULL),
--(50, 10, 'CREATED', 2, '{"resourceType":"NETWORK_INTERFACE"}', 0, NULL);